import React from 'react'
import { useState } from 'react'

const Test = () => {
    const [time, settime] = useState(Math.floor(Math.random()*20))
  const link = `https://robohash.org/${time}`
  return (
    <div>
  <button onclick="{()="> settime(Math.floor(Math.random()*100)){'}'}&gt;change</button>
  <img src="{link}/" />
  <div>{'{'}link{'}'}</div>
  Share
  Improve this answer
  Follow
  edited Feb 25, 2013 at 22:27
  answered Feb 19, 2013 at 8:50
  user avatar
  Marz
  38155 silver badges1010 bronze badges
  1
  this won't work. Say the screen size is 1200px. The page width is 1000px. If you apply a column class to a fixed element which gives say 10% width, then the fixed element will get a width of 10% of 1200px = 120px. This is because elements with position:fixed have their width calculated with respect to the viewport, not the parent divs. Whereas anything which is not fixed position will get a width of 10% of 1000px = 100px. – 
  kumarharsh
  Apr 18, 2013 at 10:21
  Add a comment
  3
  Seems to me that if you're going to have a component of the page that's fixed anyway, the easiest thing to do is just pull that div out of the 'Foundation' grid alt=""ogether. Then, outside of the grid, you can position it as fixed and it won't interact with the grid at all. If the menu itself also needs to be a flexible grid, make it one—just make it separate from the main grid.
  Share
  Improve this answer
  Follow
  edited Jun 1, 2016 at 20:18
  user avatar
  Yass
  2,63033 gold badges1212 silver badges2121 bronze badges
  answered Mar 21, 2012 at 8:57
  user1282270
  Add a comment
  Your Answer
  Sign up or log in
  Post as a guest
  Name
  Email
  Required, but never shown
  By clicking “Post Your Answer”, you agree to our terms of service, privacy policy and cookie policy
  Not the answer you're looking for? Browse other questions tagged html css css-position zurb-foundation grid-layout or ask your own question.
  The Overflow Blog
  A beginner’s guide to JSON, the data format for the internet
  Episode 448: Kidnapping an NFT
  Featured on Meta
  Announcing the arrival of Valued Associate #1214: Dalmarus
  Improvements to site status and incident communication
  Collectives Update: Introducing Bulletins
  Should we burninate the [bottom] tag?
  Ask Wizard Test Results and Next Steps
  Retiring Our Community-Specific Closure Reasons for Server Fault and Super User
  Linked
  0
  Foundation Columns when using Position:fixed forces an overlapp
  Related
  755
  Fixed position but relative to container
  6
  Padding content inside grid column layout
  0
  Changing a columns width from 60% to 100% on media queries change
  3
  overlapping div in Zurb Foundation
  408
  Responsive font size in CSS
  0
  Fixed 3 columns layout Zurb Foundation css
  0
  Responsive Grid with fixed size columns
  93
  Make column fixed position in bootstrap
  2
  Using Bootstrap grid with fixed position div
  27
  How to make a fixed column in CSS using CSS Grid Layout?
  Hot Network Questions
  Where is DOS stored in memory when a program starts?
  Electric potential generated by spherical symmetric charge density
  Can two effects of the Holy Symbol of Ravenkind be active at once?
  Generate an HTML table using JavaScript from an array of objects
  Nintendo Switch for a transatlantic traveller - what factors to consider?
  How Linux kernel sees the filesystems
  How can I modify the size of fraction?
  Why would a jury award more punitive damages than what the law allows?
  Why can't President Biden sign an executive order on the gun laws he wants congress to pass?
  Why can Canada\’s parliament vote (on gun laws), but even when a single party controls both the U.S. House and Senate a change is all but impossible?
  Why do you take the sqrt of 1/n for RMSE?
  How do you place a multi-page PDF into only 1 page in 1 spread InDesign?
  Is it possible to set the padding character for the printf function of gawk?
  Is there space in an average animal cell that I could cram some extra organelles into?
  ...all I could think of was... The Of using that I couldn't understand
  What is the difference (if any) between "fourier transform" and "SO(3) fourier transform"?
  Should I let my coworkers know I can understand their language?
  Absolute Galois group, number theory and the Axiom of Choice
  PGF/TiKZ: When should I choose "--", "to" or "edge" to connect nodes?
  Boost converter inductor calculation
  Accidentally deleted log file of running process `python something.py 21 | tee .log`. Is there a way to still save the output on the tmux-pane?
  "Moving" clocks
  To Jews in Jesus' time, what did "the Son of Man" mean?
  Would it be possible to have 3 planets that could be colonised by humans in the same system?
  Question feed
  STACK OVERFLOW
  Questions
  Help
  PRODUCTS
  Teams
  Advertising
  Collectives
  Talent
  COMPANY
  About
  Press
  Work Here
  Legal
  Privacy Policy
  Terms of Service
  Contact Us
  Cookie Settings
  Cookie Policy
  STACK EXCHANGE NETWORK
  Technology
  Culture &amp; recreation
  Life &amp; arts
  Science
  Professional
  Business
  API
  Data
  Blog
  Facebook
</div>

  )
}

export default test